// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegiaoIbge.App;

namespace RegiaoIbge.App.Migrations
{
    [DbContext(typeof(IbgeContext))]
    partial class IbgeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("RegiaoIbge.App.Cidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodigoMunicipio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mesorregiao")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeMunicipio")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Uf")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Cidades");
                });
#pragma warning restore 612, 618
        }
    }
}
